import express from "express";
import http from "http";
import WebSocket,{WebSocketServer} from "ws";
const app=express(),server=http.createServer(app),PORT=process.env.PORT||3000,clients=new Set();
const trades=[],liqs=[],books={BTC:{},ETH:{}},seen=new Set(),LIMIT=50000;
const state={}; const now=()=>Date.now();
const init=n=>state[n]??={socket:"connecting",lastTrade:0,lastBook:0,lastLiq:0,error:""};
["Binance","Bybit","OKX","Hyperliquid","Bitget"].forEach(init);
function emit(type,data){const s=JSON.stringify({type,data});for(const c of clients)if(c.readyState===WebSocket.OPEN)c.send(s)}
function putTrade(exchange,asset,side,price,qty,id,ts){price=+price;qty=+qty;const usd=price*qty,key=exchange+":"+id;if(!Number.isFinite(usd)||usd<=0||seen.has(key))return;seen.add(key);if(seen.size>100000)seen.clear();const x={exchange,asset,side,price,qty,usd,id:String(id),ts:+ts||now()};trades.push(x);if(trades.length>LIMIT)trades.shift();state[exchange].lastTrade=now();emit("trade",x)}
function putLiq(exchange,asset,side,price,qty,ts){price=+price;qty=+qty;const usd=price*qty;if(!(usd>0))return;const x={exchange,asset,side,price,qty,usd,ts:+ts||now()};liqs.push(x);if(liqs.length>10000)liqs.shift();state[exchange].lastLiq=now();emit("liquidation",x)}
function putBook(exchange,asset,bids,asks){books[asset][exchange]={bids,asks,ts:now()};state[exchange].lastBook=now();emit("book",{exchange,asset,bids,asks,ts:now()})}
function connect(name,make){let delay=1000;const go=()=>{state[name].socket="connecting";try{const ws=make();ws.on("open",()=>{state[name].socket="connected";delay=1000});ws.on("error",e=>{state[name].error=String(e.message||e).slice(0,120);try{ws.close()}catch{}});ws.on("close",()=>{state[name].socket="reconnecting";setTimeout(go,delay);delay=Math.min(30000,delay*2)})}catch(e){state[name].error=String(e);setTimeout(go,delay)}};go()}
function health(){let o={};for(const [k,v] of Object.entries(state)){const age=v.lastTrade?now()-v.lastTrade:null;o[k]={...v,tradeAgeMs:age,status:v.socket!=="connected"?"OFFLINE":age!==null&&age<60000?"LIVE":"NO_DATA"}}return o}

// Binance
connect("Binance",()=>{const ws=new WebSocket("wss://fstream.binance.com/stream?streams=btcusdt@aggTrade/ethusdt@aggTrade/btcusdt@forceOrder/ethusdt@forceOrder/btcusdt@depth20@500ms/ethusdt@depth20@500ms");ws.on("message",b=>{try{const j=JSON.parse(b),x=j.data,st=j.stream||"",A=st.startsWith("eth")?"ETH":"BTC";if(st.includes("@aggTrade"))putTrade("Binance",A,x.m?"SELL":"BUY",x.p,x.q,x.a,x.T);else if(st.includes("@forceOrder")){const o=x.o;putLiq("Binance",A,o.S,+o.ap||+o.p,o.q,o.T)}else if(st.includes("@depth20"))putBook("Binance",A,(x.b||[]).map(v=>[+v[0],+v[1]]),(x.a||[]).map(v=>[+v[0],+v[1]]))}catch(e){state.Binance.error=String(e)}});return ws});

// Bybit with orderbook delta merge
const bb={BTC:{b:new Map(),a:new Map()},ETH:{b:new Map(),a:new Map()}};
connect("Bybit",()=>{const ws=new WebSocket("wss://stream.bybit.com/v5/public/linear");ws.on("open",()=>ws.send(JSON.stringify({op:"subscribe",args:["publicTrade.BTCUSDT","publicTrade.ETHUSDT","allLiquidation.BTCUSDT","allLiquidation.ETHUSDT","orderbook.50.BTCUSDT","orderbook.50.ETHUSDT"]})));ws.on("message",b=>{try{const j=JSON.parse(b),t=j.topic||"";if(t.startsWith("publicTrade"))for(const x of j.data||[])putTrade("Bybit",x.s.startsWith("ETH")?"ETH":"BTC",String(x.S).toUpperCase(),x.p,x.v,x.i,x.T);else if(t.startsWith("allLiquidation"))for(const x of j.data||[])putLiq("Bybit",x.s.startsWith("ETH")?"ETH":"BTC",x.S,x.p,x.v,x.T);else if(t.startsWith("orderbook")&&j.data){const A=j.data.s.startsWith("ETH")?"ETH":"BTC",ob=bb[A];if(j.type==="snapshot"){ob.b.clear();ob.a.clear()}for(const [p,q] of j.data.b||[]){+q===0?ob.b.delete(p):ob.b.set(p,+q)}for(const [p,q] of j.data.a||[]){+q===0?ob.a.delete(p):ob.a.set(p,+q)}putBook("Bybit",A,[...ob.b].map(([p,q])=>[+p,q]).sort((a,b)=>b[0]-a[0]).slice(0,50),[...ob.a].map(([p,q])=>[+p,q]).sort((a,b)=>a[0]-b[0]).slice(0,50))}}catch(e){state.Bybit.error=String(e)}});return ws});

// OKX: correct USDT swap contract value
const cv={BTC:.01,ETH:.1};
connect("OKX",()=>{const ws=new WebSocket("wss://ws.okx.com:8443/ws/v5/public");ws.on("open",()=>ws.send(JSON.stringify({op:"subscribe",args:["BTC-USDT-SWAP","ETH-USDT-SWAP"].flatMap(instId=>[{channel:"trades",instId},{channel:"books5",instId}])})));ws.on("message",b=>{try{const j=JSON.parse(b),A=(j.arg?.instId||"").startsWith("ETH")?"ETH":"BTC";if(j.arg?.channel==="trades")for(const x of j.data||[])putTrade("OKX",A,x.side==="buy"?"BUY":"SELL",x.px,+x.sz*cv[A],x.tradeId,x.ts);if(j.arg?.channel==="books5"&&j.data?.[0]){const d=j.data[0];putBook("OKX",A,(d.bids||[]).map(v=>[+v[0],+v[1]*cv[A]]),(d.asks||[]).map(v=>[+v[0],+v[1]*cv[A]]))}}catch(e){state.OKX.error=String(e)}});return ws});

// Hyperliquid
connect("Hyperliquid",()=>{const ws=new WebSocket("wss://api.hyperliquid.xyz/ws");ws.on("open",()=>["BTC","ETH"].forEach(coin=>{ws.send(JSON.stringify({method:"subscribe",subscription:{type:"trades",coin}}));ws.send(JSON.stringify({method:"subscribe",subscription:{type:"l2Book",coin}}))}));ws.on("message",b=>{try{const j=JSON.parse(b);if(j.channel==="trades"){const arr=Array.isArray(j.data)?j.data:(Array.isArray(j.data?.trades)?j.data.trades:[]);for(const x of arr)putTrade("Hyperliquid",x.coin,x.side==="B"?"BUY":"SELL",x.px,x.sz,x.hash||x.tid||x.time,x.time)}if(j.channel==="l2Book"&&j.data){const A=j.data.coin,lv=j.data.levels||[[],[]];if(A==="BTC"||A==="ETH")putBook("Hyperliquid",A,(lv[0]||[]).map(x=>[+x.px,+x.sz]),(lv[1]||[]).map(x=>[+x.px,+x.sz]))}}catch(e){state.Hyperliquid.error=String(e)}});return ws});

// Bitget validated public futures trade feed
connect("Bitget",()=>{const ws=new WebSocket("wss://ws.bitget.com/v2/ws/public");ws.on("open",()=>ws.send(JSON.stringify({op:"subscribe",args:[{instType:"USDT-FUTURES",channel:"trade",instId:"BTCUSDT"},{instType:"USDT-FUTURES",channel:"trade",instId:"ETHUSDT"}]})));ws.on("message",b=>{try{const j=JSON.parse(b);if(j.arg?.channel!=="trade")return;const A=j.arg.instId.startsWith("ETH")?"ETH":"BTC";for(const x of j.data||[])putTrade("Bitget",A,x.side==="buy"?"BUY":"SELL",x.price,x.size,x.tradeId||x.ts,x.ts)}catch(e){state.Bitget.error=String(e)}});return ws});

function zones(asset){
 const px=(()=>{for(let i=trades.length-1;i>=0;i--)if(trades[i].asset===asset)return trades[i].price;return 0})();if(!px)return[];
 // Model-only levels: no fake dollar liquidity labels.
 return [10,25,50,100].flatMap(L=>[{side:"LONG",lev:L,price:px*(1-1/L)},{side:"SHORT",lev:L,price:px*(1+1/L)}]);
}
app.get("/health",(_,r)=>r.json({ok:true,uptime:process.uptime(),sources:health(),buffer:trades.length}));
app.get("/api/snapshot",(_,r)=>{const c=now()-86400000;r.json({trades:trades.filter(x=>x.ts>=c).slice(-15000),liquidations:liqs.filter(x=>x.ts>=c),books,health:health(),zones:{BTC:zones("BTC"),ETH:zones("ETH")}})});

app.get("/",(_,r)=>r.type("html").send(`<!doctype html><html lang="zh-Hant"><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>WhaleScope</title><style>
*{box-sizing:border-box}body{margin:0;background:#030711;color:#eaf1ff;font-family:system-ui;background-image:radial-gradient(circle at 50% 0,#1b0c4e55,transparent 38%)}main{max-width:1500px;margin:auto;padding:14px}.head{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.logo{font-size:30px;font-weight:900;color:#b45cff}select{background:#081020;border:1px solid #24466d;color:white;padding:10px;border-radius:9px}.cards,.grid,.flow{display:grid;gap:10px;margin-top:10px}.cards{grid-template-columns:repeat(4,1fr)}.grid{grid-template-columns:1.15fr 1fr}.flow{grid-template-columns:repeat(4,1fr)}.card{background:#06101de8;border:1px solid #173c63;border-radius:13px;padding:14px}.title{font-size:18px;font-weight:800;margin-bottom:10px}.label,.muted{color:#8fa1c4;font-size:12px}.big{font-size:27px;font-weight:900}.g{color:#35efa6}.r{color:#ff5a78}.p{color:#a86cff}.scroll{max-height:390px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}td,th{padding:8px 5px;border-bottom:1px solid #12233d;text-align:right}td:first-child,th:first-child{text-align:left}.pill{display:inline-block;padding:5px 8px;border:1px solid #274e77;border-radius:20px;margin:3px;font-size:11px}.heat{height:300px;position:relative;border:1px solid #17304f;border-radius:9px;overflow:hidden}.z{position:absolute;left:0;right:0;height:12px;padding-left:7px;font-size:10px;transform:translateY(-50%)}.zl{background:linear-gradient(90deg,#16e99b22,#16e99bcc,#16e99b22)}.zs{background:linear-gradient(90deg,#ff557522,#ff5575cc,#ff557522)}.bar{height:8px;background:#10213a;border-radius:8px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,#24e4a3,#8c62ff)}@media(max-width:750px){.cards,.grid,.flow{grid-template-columns:1fr 1fr}}@media(max-width:520px){.grid,.flow{grid-template-columns:1fr}}
</style></head><body><main><div class=head><div><div class=logo>◉ WhaleScope</div><div class=muted>Verified CEX + On-chain Intelligence</div></div><select id=a><option>BTC</option><option>ETH</option></select><select id=t><option value=100000>$100K+</option><option value=500000 selected>$500K+</option><option value=1000000>$1M+</option></select><b class=g>● <span id=live>CHECKING</span></b></div>
<div class=cards><div class=card><div class=label>24H 巨鯨成交</div><div id=total class=big>$0</div></div><div class=card><div class=label>24H 主動買入</div><div id=buy class="big g">$0</div></div><div class=card><div class=label>24H 主動賣出</div><div id=sell class="big r">$0</div></div><div class=card><div class=label>資金淨流入</div><div id=net class="big p">$0</div></div></div>
<div class=grid><div class=card><div class=title>巨鯨大額成交</div><div class=scroll><table><thead><tr><th>時間</th><th>方向</th><th>金額</th><th>來源</th></tr></thead><tbody id=tr></tbody></table></div></div><div class=card><div class=title>大戶掛單點位</div><div class=scroll><table><thead><tr><th>類型</th><th>價格</th><th>金額</th><th>來源</th></tr></thead><tbody id=wa></tbody></table></div></div></div>
<div class=grid><div class=card><div class=title>清算槓桿參考區</div><div id=heat class=heat></div><div class=muted>10x/25x/50x/100x 為價格槓桿參考區，不再顯示虛構的清算金額。實際熱圖後續需接 OI/清算模型資料。</div></div><div class=card><div class=title>實際公開強平</div><div id=liq class=scroll></div></div></div>
<div class=grid><div class=card><div class=title>交易所成交資金分布</div><div id=ven></div><div class=muted>只計入真正收到且成功解析的公開成交資料。</div></div><div class=card><div class=title>資料來源驗證</div><div id=src></div></div></div>
<div class=card style="margin-top:10px"><div class=title>資金流向 · MONEY FLOW</div><div id=flow class=flow></div></div>
</main><script>
let D={trades:[],liquidations:[],books:{BTC:{},ETH:{}},health:{},zones:{BTC:[],ETH:[]}};const $=x=>document.getElementById(x),M=n=>"$"+Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:2}).format(n||0);
function C(min,A,T){let x=D.trades.filter(v=>v.asset===A&&v.usd>=T&&v.ts>Date.now()-min*60000),b=x.filter(v=>v.side==="BUY").reduce((s,v)=>s+v.usd,0),s=x.filter(v=>v.side==="SELL").reduce((q,v)=>q+v.usd,0);return{x,b,s,n:b-s}}
function draw(){let A=$("a").value,T=+$("t").value,q=C(1440,A,T);$("total").textContent=M(q.b+q.s);$("buy").textContent=M(q.b);$("sell").textContent=M(q.s);$("net").textContent=(q.n>=0?"+":"")+M(q.n);$("tr").innerHTML=q.x.slice(-40).reverse().map(v=>"<tr><td>"+new Date(v.ts).toLocaleTimeString()+"</td><td class="+(v.side==="BUY"?"g":"r")+">"+v.side+"</td><td>"+M(v.usd)+"</td><td>"+v.exchange+"</td></tr>").join("")||"<tr><td colspan=4 class=muted>等待符合門檻的成交…</td></tr>";
let w=[];for(const [e,b] of Object.entries(D.books[A]||{})){for(const [p,z] of b.bids||[])if(p*z>=T)w.push({s:"BID",p,u:p*z,e});for(const [p,z] of b.asks||[])if(p*z>=T)w.push({s:"ASK",p,u:p*z,e})}w.sort((a,b)=>b.u-a.u);$("wa").innerHTML=w.slice(0,50).map(x=>"<tr><td class="+(x.s==="BID"?"g":"r")+">"+x.s+"</td><td>"+x.p.toLocaleString()+"</td><td>"+M(x.u)+"</td><td>"+x.e+"</td></tr>").join("")||"<tr><td colspan=4 class=muted>目前沒有符合門檻掛單</td></tr>";
let z=D.zones[A]||[],ps=z.map(x=>x.price),last=D.trades.filter(x=>x.asset===A).at(-1)?.price||0,lo=Math.min(last*.88,...ps),hi=Math.max(last*1.12,...ps),sp=hi-lo||1;$("heat").innerHTML=z.map(x=>"<div class='z "+(x.side==="LONG"?"zl":"zs")+"' style='top:"+((hi-x.price)/sp*100)+"%'>"+x.side+" "+x.lev+"x · "+x.price.toFixed(0)+"</div>").join("");
$("liq").innerHTML=D.liquidations.filter(x=>x.asset===A).slice(-30).reverse().map(x=>"<div style='padding:7px;border-bottom:1px solid #13243d'><b class="+(x.side==="BUY"?"g":"r")+">"+x.side+"</b> "+x.exchange+" <span style=float:right>"+M(x.usd)+" @ "+x.price.toLocaleString()+"</span></div>").join("")||"<div class=muted>等待 Binance / Bybit 公開強平事件…</div>";
let by={};for(const x of q.x)by[x.exchange]=(by[x.exchange]||0)+x.usd;let mx=Math.max(1,...Object.values(by));$("ven").innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([e,v])=>"<div style='margin:9px 0'>"+e+" <span style=float:right>"+M(v)+"</span><div class=bar><i style='width:"+(v/mx*100)+"%'></i></div></div>").join("")||"<div class=muted>等待符合門檻成交…</div>";
let hs=Object.entries(D.health),live=hs.filter(([e,v])=>v.status==="LIVE").length;$("live").textContent=live+"/"+hs.length+" VERIFIED LIVE";$("src").innerHTML=hs.map(([e,v])=>"<span class=pill>"+e+" · "+v.status+(v.tradeAgeMs!=null?" · "+Math.round(v.tradeAgeMs/1000)+"s":"")+"</span>").join("");
$("flow").innerHTML=[[5,"5m"],[15,"15m"],[60,"1h"],[1440,"24h"]].map(([m,n])=>{let x=C(m,A,T);return"<div class=card><div class=label>"+n+" NET</div><div class='big "+(x.n>=0?"g":"r")+"'>"+(x.n>=0?"+":"")+M(x.n)+"</div><div class=muted>BUY "+M(x.b)+" / SELL "+M(x.s)+"</div></div>"}).join("")}
async function snap(){try{D=await fetch("/api/snapshot",{cache:"no-store"}).then(r=>r.json());draw()}catch(e){$("live").textContent="API ERROR"}}snap();setInterval(snap,5000);$("a").onchange=draw;$("t").onchange=draw;
const ws=new WebSocket((location.protocol==="https:"?"wss://":"ws://")+location.host+"/ws");ws.onmessage=e=>{let j=JSON.parse(e.data);if(j.type==="trade"){D.trades.push(j.data);if(D.trades.length>15000)D.trades.shift()}else if(j.type==="liquidation")D.liquidations.push(j.data);else if(j.type==="book"){D.books[j.data.asset]??={};D.books[j.data.asset][j.data.exchange]=j.data}draw()};
</script></body></html>`));
const wss=new WebSocketServer({server,path:"/ws"});wss.on("connection",ws=>{clients.add(ws);ws.on("close",()=>clients.delete(ws))});
setInterval(()=>{const c=now()-86400000;while(trades.length&&trades[0].ts<c)trades.shift();while(liqs.length&&liqs[0].ts<c)liqs.shift()},60000);
server.listen(PORT,"0.0.0.0",()=>console.log("WhaleScope v5 verified pipeline on",PORT));
